language: go
go:
  # webgo is still compatible with 1.8, but the tests are importing versioned 
  # modules which fails for older Go versions and using `errors.Is` which was introduced in Go 1.13
  # - "1.8"
  - "1.13"
  - master

before_install:
  - go get -t -v ./...

script:
  # go.mod is overwritten to avoid go version being part of the mod file, which fails tests on mismatching version
  - sed -i 's/go [0-9]*\.[0-9]*//' go.mod
  - go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)

after_success:
  - bash <(curl -s https://codecov.io/bash)