name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  testold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.13
        uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)

  testlatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go latest
        uses: actions/setup-go@v3
        with:
          go-version: latest

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)
