name: Webgo tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)
      # - run: sed -i 's/go [0-9]*\.[0-9]*//' go.mod
