run-name: Tests & Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Tests
    permissions: read
    runs-on: ubuntu-latest
    steps:
      uses: docker://golang:1.13
      run: sed -i 's/go [0-9]*\.[0-9]*//' go.mod
      run: go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)
