run-name: Tests & Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    steps:
      - run: echo $PWD
      - run: cd ..
      - run: echo $PWD
      - run: ls -lah
      - run: sed -i 's/go [0-9]*\.[0-9]*//' go.mod
      - run: go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)
